"use client";
import { useEffect, useMemo, useState } from "react";
import heroesJson from "@/src/data/heroes.json";
import type { HeroesData } from "@/src/types";
type Platform = "PC" | "Console"; type Window = "all" | "recent"; type VoteRow = { abilityId: string; rank: string; total: number }; type Totals = Record<string, number>;
const heroes = (heroesJson as HeroesData).heroes;
const eras = [{ season: "Season 09", patch: "S9 Launch", label: "S9 · LAUNCH" }, { season: "Season 08", patch: "Final Balance", label: "S8 · FINAL" }] as const;
function collapse(rows: VoteRow[]) { return rows.reduce<Totals>((all, row) => ({ ...all, [row.abilityId]: (all[row.abilityId] ?? 0) + row.total }), {}); }
export default function PatchDashboard() {
  const [platform, setPlatform] = useState<Platform>("PC"); const [window, setWindow] = useState<Window>("all"); const [current, setCurrent] = useState<Totals>({}); const [previous, setPrevious] = useState<Totals>({}); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); Promise.all(eras.map(async (era) => { const params = new URLSearchParams({ season: era.season, patch: era.patch, window, platform }); const response = await fetch(`/api/votes?${params}`, { cache: "no-store" }); const data = response.ok ? await response.json() as { votes: VoteRow[] } : { votes: [] }; return collapse(data.votes); })).then(([next, prior]) => { setCurrent(next); setPrevious(prior); }).finally(() => setLoading(false)); }, [platform, window]);
  const rows = useMemo(() => heroes.map((hero) => { const [a,b] = hero.teamUpAbilities; const av=current[a.id]??0,bv=current[b.id]??0,total=av+bv; const leader=av>=bv?a:b, leaderVotes=Math.max(av,bv), percent=total?Math.round(leaderVotes/total*100):50; const pa=previous[a.id]??0,pb=previous[b.id]??0,pt=pa+pb, priorLeader=pt?(pa>=pb?a:b):null; return { hero,leader,percent,total,margin:Math.abs(av-bv),changed:Boolean(priorLeader&&priorLeader.id!==leader.id),priorTotal:pt }; }).sort((a,b)=>b.total-a.total||b.margin-a.margin),[current,previous]);
  const totalVotes=rows.reduce((sum,row)=>sum+row.total,0), active=rows.filter(row=>row.total>0), closeRaces=active.filter(row=>row.percent<=55).length, changed=rows.filter(row=>row.changed).length;
  return <main className="legal-shell patch-shell"><header className="topbar detail-topbar"><a className="brand" href="/"><span className="brand-mark">R</span><span><strong>RIVALS</strong><small>TEAM-UP META</small></span></a><nav className="role-nav"><a href="/roles/vanguards">Vanguards</a><a href="/roles/duelists">Duelists</a><a href="/roles/strategists">Strategists</a></nav><a className="detail-back" href="/">← DIRECTORY</a></header>
  <section className="patch-hero"><p className="eyebrow">LIVE PATCH INTELLIGENCE</p><h1>TEAM-UP<br/><span>SHIFT REPORT</span></h1><p>Track the community meta without mixing votes from different balance eras. Compare current leaders, identify contested Team-Ups, and see when preferences move after an update.</p></section>
  <section className="patch-controls"><div><span>PLATFORM</span><button className={platform==="PC"?"is-active":""} onClick={()=>setPlatform("PC")}>PC</button><button className={platform==="Console"?"is-active":""} onClick={()=>setPlatform("Console")}>CONSOLE</button></div><div><span>RESULT WINDOW</span><button className={window==="all"?"is-active":""} onClick={()=>setWindow("all")}>ALL-TIME</button><button className={window==="recent"?"is-active":""} onClick={()=>setWindow("recent")}>LAST 30 DAYS</button></div></section>
  <section className="patch-stat-grid"><article><span>RECORDED VOTES</span><strong>{totalVotes.toLocaleString()}</strong><p>{eras[0].label} · {platform}</p></article><article><span>ACTIVE HERO RACES</span><strong>{active.length}</strong><p>Heroes with recorded votes</p></article><article><span>CLOSE RACES</span><strong>{closeRaces}</strong><p>Leader at 55% or less</p></article><article><span>LEADER CHANGES</span><strong>{changed}</strong><p>Compared with {eras[1].label}</p></article></section>
  <section className="patch-report"><div className="patch-report-heading"><div><p className="eyebrow">CURRENT CONSENSUS</p><h2>{eras[0].label} TEAM-UP LEADERS</h2></div><p>{loading?"Loading live community results…":`${platform} · ${window==="recent"?"last 30 days":"all-time"}`}</p></div><div className="patch-table">{rows.map(({hero,leader,percent,total,margin,changed,priorTotal})=><a href={`/heroes/${hero.id}`} key={hero.id}><img src={`/heroes/${hero.id}.webp`} alt=""/><div><span>{hero.role}</span><strong>{hero.name}</strong><small>{leader.name} · {leader.anchorPartner}</small></div><div className="patch-result"><strong>{percent}%</strong><span>{total.toLocaleString()} VOTES</span></div><div className="patch-signal">{total===0?"AWAITING DATA":changed?"LEADER CHANGED":margin<=Math.max(2,total*.1)?"CLOSE RACE":priorTotal?"LEADER HELD":"CURRENT LEADER"}</div></a>)}</div></section>
  <section className="patch-method"><h2>HOW PATCH HISTORY WORKS</h2><div><article><span>01</span><h3>Votes stay with their patch</h3><p>Earlier votes remain attached to their original season and patch instead of being blended into the new meta.</p></article><article><span>02</span><h3>Recent results reveal momentum</h3><p>Use the 30-day view to spot developing preferences before they become the all-time community leader.</p></article><article><span>03</span><h3>Platforms stay separate</h3><p>PC and console voting can be compared independently because play patterns may influence Team-Up preference.</p></article></div></section></main>;
}
