"use client";
import { useEffect, useMemo, useState } from "react";
import heroesJson from "@/src/data/heroes.json";
import type { HeroesData } from "@/src/types";
type Platform = "PC" | "Console"; type Window = "all" | "recent"; type VoteRow = { abilityId: string; rank: string; total: number }; type Totals = Record<string, number>;
const heroes = (heroesJson as HeroesData).heroes;
const era = { season: "Season 09", patch: "S9 Launch", label: "S9 · LAUNCH" } as const;
function collapse(rows: VoteRow[]) { return rows.reduce<Totals>((all, row) => ({ ...all, [row.abilityId]: (all[row.abilityId] ?? 0) + row.total }), {}); }
export default function PatchDashboard() {
  const [platform, setPlatform] = useState<Platform>("PC"); const [window, setWindow] = useState<Window>("all"); const [current, setCurrent] = useState<Totals>({}); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); const params = new URLSearchParams({ season: era.season, patch: era.patch, window, platform }); fetch(`/api/votes?${params}`, { cache: "no-store" }).then(async (response) => response.ok ? await response.json() as { votes: VoteRow[] } : { votes: [] }).then((data) => setCurrent(collapse(data.votes))).finally(() => setLoading(false)); }, [platform, window]);
  const rows = useMemo(() => heroes.map((hero) => { const [a,b] = hero.teamUpAbilities; const av=current[a.id]??0,bv=current[b.id]??0,total=av+bv; const leader=av>=bv?a:b, leaderVotes=Math.max(av,bv), percent=total?Math.round(leaderVotes/total*100):50; return { hero,leader,percent,total,margin:Math.abs(av-bv) }; }).sort((a,b)=>b.total-a.total||b.margin-a.margin),[current]);
  const totalVotes=rows.reduce((sum,row)=>sum+row.total,0), active=rows.filter(row=>row.total>0), closeRaces=active.filter(row=>row.percent<=55).length, decisive=active.filter(row=>row.percent>=65).length;
  return <main className="legal-shell patch-shell"><header className="topbar detail-topbar"><a className="brand" href="/"><span className="brand-mark">R</span><span><strong>RIVALS</strong><small>TEAM-UP</small></span></a><nav className="role-nav"><a href="/roles/vanguards">Vanguards</a><a href="/roles/duelists">Duelists</a><a href="/roles/strategists">Strategists</a></nav><a className="detail-back" href="/">← DIRECTORY</a></header>
  <section className="patch-hero"><p className="eyebrow">LIVE PATCH INTELLIGENCE</p><h1>TEAM-UP<br/><span>SHIFT REPORT</span></h1><p>Track the community meta without mixing votes from different balance eras. Compare current leaders, identify contested Team-Ups, and see when preferences move after an update.</p></section>
  <section className="patch-controls"><div><span>PLATFORM</span><button className={platform==="PC"?"is-active":""} onClick={()=>setPlatform("PC")}>PC</button><button className={platform==="Console"?"is-active":""} onClick={()=>setPlatform("Console")}>CONSOLE</button></div><div><span>RESULT WINDOW</span><button className={window==="all"?"is-active":""} onClick={()=>setWindow("all")}>ALL-TIME</button><button className={window==="recent"?"is-active":""} onClick={()=>setWindow("recent")}>LAST 30 DAYS</button></div></section>
  <section className="patch-stat-grid"><article><span>RECORDED VOTES</span><strong>{totalVotes.toLocaleString()}</strong><p>{era.label} · {platform}</p></article><article><span>ACTIVE HERO RACES</span><strong>{active.length}</strong><p>Heroes with recorded votes</p></article><article><span>CLOSE RACES</span><strong>{closeRaces}</strong><p>Leader at 55% or less</p></article><article><span>DECISIVE LEADERS</span><strong>{decisive}</strong><p>Leader at 65% or more</p></article></section>
  <section className="patch-report"><div className="patch-report-heading"><div><p className="eyebrow">CURRENT CONSENSUS</p><h2>{era.label} TEAM-UP LEADERS</h2></div><p>{loading?"Loading live community results…":`${platform} · ${window==="recent"?"last 30 days":"all-time"}`}</p></div><div className="patch-table">{rows.map(({hero,leader,percent,total,margin})=><a href={`/heroes/${hero.id}`} key={hero.id}><img src={`/heroes/${hero.id}.webp`} alt=""/><div><span>{hero.role}</span><strong>{hero.name}</strong><small>{leader.name} · {leader.anchorPartner}</small></div><div className="patch-result"><strong>{percent}%</strong><span>{total.toLocaleString()} VOTES</span></div><div className="patch-signal">{total===0?"AWAITING DATA":margin<=Math.max(2,total*.1)?"CLOSE RACE":percent>=65?"STRONG CONSENSUS":"CURRENT LEADER"}</div></a>)}</div></section>
  <section className="patch-method"><h2>HOW PATCH HISTORY WORKS</h2><div><article><span>01</span><h3>Votes stay with their patch</h3><p>Earlier votes remain attached to their original season and patch instead of being blended into the new meta.</p></article><article><span>02</span><h3>Recent results reveal momentum</h3><p>Use the 30-day view to spot developing preferences before they become the all-time community leader.</p></article><article><span>03</span><h3>Platforms stay separate</h3><p>PC and console voting can be compared independently because play patterns may influence Team-Up preference.</p></article></div></section>
  <footer className="detail-legal-footer"><span>RIVALS TEAM-UPS // PATCH INTELLIGENCE</span><nav className="legal-links"><a href="/contact">CONTACT</a><a href="/legal-notice">LEGAL NOTICE</a><a href="/privacy-policy">PRIVACY</a><a href="/terms-of-use">TERMS</a><a href="/cookie-policy">COOKIES</a></nav><a href="/">DIRECTORY ↑</a></footer></main>;
}
